import React, {
  useCallback,
  useEffect,
  useMemo,
  useRef,
  useState,
  type ReactNode,
} from "react";
import type { AppNotification } from "../../types";
import { useUsers } from "../../hooks/useUsers";
import { useTickets } from "../../hooks/useTickets";
import { canManageUsers } from "../../utils/permissions";
import {
  buildDailySummaryNotification,
  getLocalDateKey,
} from "../../utils/notifications";
import { NotificationsContext } from "./context";

/**
 * In-memory notification store. Notifications are generated by event call
 * sites (ticket assignment, ticket creation) and seeded daily here for the
 * manager's end-of-day summary. Newest notifications are kept first.
 */
export const NotificationsProvider: React.FC<{ children: ReactNode }> = ({
  children,
}) => {
  const [notifications, setNotifications] = useState<AppNotification[]>([]);
  const seededByDay = useRef<Set<string>>(new Set());

  const { users, loadState: usersLoadState } = useUsers();
  const { tickets, loadState: ticketsLoadState } = useTickets();

  const addNotification = useCallback((notification: AppNotification) => {
    setNotifications((prev) =>
      prev.some((n) => n.id === notification.id)
        ? prev
        : [notification, ...prev],
    );
  }, []);

  const markAsRead = useCallback((id: string) => {
    setNotifications((prev) =>
      prev.map((n) => (n.id === id ? { ...n, read: true } : n)),
    );
  }, []);

  const markAllAsRead = useCallback(() => {
    setNotifications((prev) => prev.map((n) => ({ ...n, read: true })));
  }, []);

  // Generate the manager's daily summary once per manager per day, as soon as
  // the users and tickets datasets are available (app lifetime mock of a
  // scheduled daily job).
  useEffect(() => {
    if (usersLoadState !== "success" || ticketsLoadState !== "success") return;

    const todayKey = getLocalDateKey(new Date());
    const managers = users.filter(canManageUsers);

    managers.forEach((manager) => {
      const key = `${manager.id}:${todayKey}`;
      if (seededByDay.current.has(key)) return;
      seededByDay.current.add(key);
      addNotification(
        buildDailySummaryNotification({
          manager,
          tickets,
        }),
      );
    });
  }, [users, usersLoadState, tickets, ticketsLoadState, addNotification]);

  const value = useMemo(
    () => ({
      notifications,
      addNotification,
      markAsRead,
      markAllAsRead,
      unreadCountFor: (recipientId: string) =>
        notifications.filter((n) => n.recipientId === recipientId && !n.read)
          .length,
      notificationsFor: (recipientId: string) =>
        notifications.filter((n) => n.recipientId === recipientId),
    }),
    [notifications, addNotification, markAsRead, markAllAsRead],
  );

  return (
    <NotificationsContext.Provider value={value}>
      {children}
    </NotificationsContext.Provider>
  );
};
